# Generated by Django 4.2.5 on 2023-12-17 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("id_ref", models.UUIDField(default=uuid.uuid4)),
                ("record_name", models.TextField(blank=True, null=True)),
                ("time_stamp", models.DateTimeField(blank=True, null=True)),
                ("file_name", models.TextField(blank=True, null=True)),
                ("pred_loc", models.TextField(blank=True, null=True)),
                ("crop_loc", models.TextField(blank=True, null=True)),
                (
                    "processing_time_pred",
                    models.DecimalField(
                        blank=True, decimal_places=20, max_digits=30, null=True
                    ),
                ),
                (
                    "processing_time_ocr",
                    models.DecimalField(
                        blank=True, decimal_places=20, max_digits=30, null=True
                    ),
                ),
                ("ocr_text_result", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
