# Generated by Django 4.2.5 on 2023-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_detection_record_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detection",
            name="crop_loc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detection",
            name="file_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detection",
            name="ocr_text_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detection",
            name="pred_loc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detection",
            name="record_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
