# Generated by Django 4.2.5 on 2023-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp_creation', models.DateField(auto_created=True)),
                ('record_name', models.CharField(max_length=200)),
                ('pred_loc', models.CharField(blank=True, max_length=500, null=True)),
                ('crop_loc', models.CharField(blank=True, max_length=500, null=True)),
                ('processing_time_pred', models.IntegerField(blank=True, null=True)),
                ('processing_time_ocr', models.IntegerField(blank=True, null=True)),
                ('ocr_text_result', models.CharField(blank=True, max_length=500, null=True)),
                ('pred_json_bin', models.CharField(blank=True, max_length=500, null=True)),
                ('crop_json_bin', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
