# Generated by Django 4.2.5 on 2023-09-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_detection_processing_time_ocr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='crop_json_bin',
            new_name='crop_json_base64',
        ),
        migrations.RenameField(
            model_name='detection',
            old_name='pred_json_bin',
            new_name='pred_json_base64',
        ),
    ]
