# Generated by Django 4.2.5 on 2023-09-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_detection_crop_json_base64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='crop_loc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='pred_loc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='record_name',
            field=models.CharField(max_length=300),
        ),
    ]
