# Generated by Django 4.2.5 on 2023-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_detection_crop_json_base64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='time_stamp_creation',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
