# Generated by Django 4.2.5 on 2023-09-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_detection_time_stamp_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='time_stamp_creation',
        ),
        migrations.AddField(
            model_name='detection',
            name='time_stamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
