FROM python:3.11.6-bookworm

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN set -e; \
    apt-get update ;\
    apt-get -y install netcat-traditional ;\
    apt-get -y install gettext ;\
    apt-get -y  install httpie; \
    pip install --upgrade pip \

    RUN mkdir /code
COPY . /code/
WORKDIR /code

RUN set -e; \
    /usr/local/bin/python -m pip install --upgrade pip ;\
    python -m pip install -r /code/requirements.txt ;

ENTRYPOINT ["python", "-m","celery -A core worker -l DEBUG -P gevent"]